---
- debug: msg="{{ alias_old_platform }}"
- debug: msg="{{ item }}"
- set_fact:
    number_site: "{{ item.number }}"
- name: Clone old site to the new platform
  command: "drush @{{ alias_old_site }} provision-clone @site{{number_site}}_{{ platform }} @platform_{{ platform }}"
  become: yes
  become_user: "{{ aegir_user }}"
  when: verification_platform|success
  register: cloned_site
- debug: msg="Site @{{ alias_old_site }} cloned to    ====> @platform_{{ platform }}"
- name: Import the new cloned site to hostmaster
  command: "drush @hostmaster hosting-task @platform_{{ platform }} verify"
  become: yes
  become_user: "{{ aegir_user }}"
  when: cloned_site|success
- debug: msg="Site imported to hostmaster    ====> @platform_{{ platform }}"
- name: Enable the new site 
  command: "drush @hostmaster hosting-task @site{{number_site}}_{{ platform }} enable"
  become: yes
  become_user: "{{ aegir_user }}"
  when: cloned_site|success
  register: new_site_enabled
- debug: msg="Site enabled    ====> @site{{number_site}}_{{ platform }}"
  when: new_site_enabled|success
...