---
- set_fact:
    number_site: "{{ item.number }}"
- name: Make sure comoser_manager module enabled 
  command: "drush @site{{ number_site }}_{{ platform }} en -y composer_manager"
- name: Clear cache drush 
  command: "drush @site{{ number_site }}_{{ platform }} cc drush"
- name: Clear cache  
  command: "drush @site{{ number_site }}_{{ platform }} cc all"
- name: Rebuild composer.json dependecies
  command: "drush @site{{ number_site }}_{{ platform }} composer-json-rebuild"
- name: Composer install dependecies
  composer: 
    command: update
    optimize_autoloader: true
    working_dir: "{{aegir_home}}/platforms/{{ platform }}/sites/site{{ number_site }}_{{ platform }}/files/composer"
...