- name: Write local-settings file
  template:
    src: "{{ default_template }}local.sttings.php.j2"
    dest: "{{aegir_home}}/platforms/{{ platform }}/sites/site_{{ platform }}/local.settings.php"
    force: yes
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
...
