---
- set_fact:
    number_site: "{{ item.number }}"
    alias_domain: "{{ item.alias_domain }}"
    default_theme: "{{ item.default_theme }}"
- name: Write local-settings file
  template:
    src: "{{ default_template }}local.sttings.php.j2"
    dest: "{{aegir_home}}/platforms/{{ platform }}/sites/site{{ number_site }}-{{ platform }}/local.settings.php"
    force: yes
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
- name: Set to default theme
  command: "drush @site{{ number_site }}-{{ platform }} vset -y --format=string theme_default {{ default_theme }}"
  when: default_theme!=""
...
