---
- name: Default templates folder
  set_fact:
    default_template: "{{ override_template | default('templates/')}}"
- name: create directory
  file:
    path: tmp
    state: directory
    owner : "{{aegir_user}}"
    group: "{{aegir_user}}"
    mode: 0777
- include:  clearch_drush_composer_cache.yml
- name: Write makefile
  template:
    src: "{{ default_template }}drush-install.make.j2"
    dest: "tmp/{{ aegir_makefile }}"
    force: yes
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
- name: Drush test deploy by make file validation
  command: "drush make tmp/{{ aegir_makefile }} tmp/{{ platform }}"
  become: yes
  become_user: "{{ aegir_user }}"
  register: deployment_test
- name: delete tmp folder
  when: deployment_test|success
  shell: "rm -rf tmp/*"
- name: Get old platform
  find:
    paths: "{{aegir_home}}/platforms"
    file_type: "directory"
    patterns: "{{ destination }}_7x*"
  become: yes
  become_user: "{{ aegir_user }}"
  register: old_platforms
- name: Get the last main alias platform
  set_fact:
    old_alias: "{{ old_platforms.files | sort(reverse=true, attribute='path') | map(attribute='path') |first | replace('/var/aegir/platforms/', '') }}"
  when: old_platforms|success
  ignore_errors: yes
- debug: msg="{{ old_alias }}"
  ignore_errors: yes
- name: Set old aliases
  set_fact:
    alias_old_site: "site_{{ old_alias }}"
    alias_old_platform: "platform_{{ old_alias }}"
  when: old_platforms|success
  ignore_errors: yes
- include: deploy_platform.yml
  when: deployment_test|success
- include: clone_site_to_new_platform.yml
  with_items:
     - "{{ sites_to_clones }}"
  when: (deployment_test|success)
- include: local_setting_configuration.yml
  with_items:
     - "{{ sites_to_clones }}"
  when: (deployment_test|success and destination!="local")
- include: composer_update_task.yml
  with_items:
     - "{{ sites_to_clones }}"
  when: new_site_enabled|success
- include: move_site_alias.yml
  with_items:
     - "{{ sites_to_clones }}"
  when: new_site_enabled|success
  notify:
   - Retart Apache
...
