---
- set_fact:
    number_site: "{{ item.number }}"
    alias_domain: "{{ item.alias_domain }}"
- include: test_site_exist.yml test_site={{ alias_old_site }}
- include: set_alias_task.yml site_alias={{ alias_old_site }} domain=null
  when: move_site_alias and site_exist|success
- include: set_alias_task.yml site_alias=site{{ number_site }}-{{ platform }} domain={{ alias_domain }}
...