; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.54"

; Modules
projects[logging_alerts][version] = "2.2"

projects[autologout][version] = "4.4"

projects[ctools][version] = "1.12"

projects[ckeditor][version] = "1.17"

projects[collapsiblock][version] = "1.1"

projects[composer_manager][version] = "1.8"

projects[countries][version] = "2.3"

projects[draggableviews][version] = "2.1"

projects[entity][version] = "1.8"

projects[google_analytics][version] = "2.3"

projects[http_client][version] = "2.4"

projects[i18n][version] = "1.15"

projects[imce][version] = "1.10"

projects[jquery_update][version] = "2.7"

projects[libraries][version] = "2.3"

projects[markdown][version] = "1.5"

projects[memcache][version] = "1.5"

projects[nodequeue][version] = "2.1"

projects[smtp][version] = "1.6"

projects[variable][version] = "2.5"

projects[views][version] = "3.15"


projects[obiba_agate] = "2.3"

;projects[obiba_agate][download][type] = "git"
;projects[obiba_agate][download][branch] = "master"
;projects[obiba_agate][download][url] = "https://github.com/obiba/agate-drupal7.git"
;projects[obiba_agate][directory_name] = "obiba_agate"
;projects[obiba_agate][type] = "module"
;projects[obiba_agate][version] = "obiba_agate"

projects[obiba_mica] = "21.1"

;projects[obiba_mica][download][type] = "git"
;projects[obiba_mica][download][branch] = "master"
;projects[obiba_mica][download][url] = "https://github.com/smirfolio/mica-drupal7.git"
;projects[obiba_mica][directory_name] = "obiba_mica"
;projects[obiba_mica][type] = "module"


; Themes
projects[bootstrap][version] = "3.11"
projects[bootstrap][type] = "theme"

;
; DEV
;projects[obiba_bootstrap][download][type] = "git"
;projects[obiba_bootstrap][download][branch] = "master"
;projects[obiba_bootstrap][download][url] = "https://github.com/obiba/bootstrap-drupal7.git"
;projects[obiba_bootstrap][directory_name] = "obiba_bootstrap"
;projects[obiba_bootstrap][type] = "theme"
;projects[obiba_bootstrap][version] = "master"

projects[obiba_bootstrap] = "4.2"


; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[datatables][download][type] = "file"
libraries[datatables][download][url] = "https://github.com/obiba/mica-drupal-js-libraries/archive/2.1.3.zip"
libraries[datatables][download][subtree] = "mica-drupal-js-libraries-2.1.3/datatables"
libraries[datatables][type] = "library"
libraries[datatables][directory_name] = "datatables"

libraries[angular-app][download][type] = "file"
libraries[angular-app][download][url] = "https://github.com/obiba/mica-drupal-js-libraries/archive/2.1.3.zip"
libraries[angular-app][download][subtree] = "mica-drupal-js-libraries-2.1.3/angular-app"
libraries[angular-app][type] = "library"
libraries[angular-app][directory_name] = "angular-app"


libraries[obiba-progressbar][download][type] = "file"
libraries[obiba-progressbar][download][url] = "https://github.com/obiba/mica-drupal-js-libraries/archive/2.1.3.zip"
libraries[obiba-progressbar][download][subtree] = "mica-drupal-js-libraries-2.1.3/obiba-progressbar"
libraries[obiba-progressbar][type] = "library"
libraries[obiba-progressbar][directory_name] = "obiba-progressbar"

libraries[mica-study-timeline][download][type] = "file"
libraries[mica-study-timeline][download][url] = "https://github.com/obiba/mica-drupal-js-libraries/archive/2.1.3.zip"
libraries[mica-study-timeline][download][subtree] = "mica-drupal-js-libraries-2.1.3/mica-study-timeline"
libraries[mica-study-timeline][type] = "library"
libraries[mica-study-timeline][directory_name] = "mica-study-timeline"

libraries[obiba-country-codes][download][type] = "file"
libraries[obiba-country-codes][download][url] = "https://github.com/obiba/mica-drupal-js-libraries/archive/2.1.3.zip"
libraries[obiba-country-codes][download][subtree] = "mica-drupal-js-libraries-2.1.3/obiba-country-codes"
libraries[obiba-country-codes][type] = "library"
libraries[obiba-country-codes][directory_name] = "obiba-country-codes"